objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    openvswitch_bond:
      description: Manage Open vSwitch bonds
      name: openvswitch_bond
      namespace: ""
      version_added: 1.0.0
    openvswitch_bridge:
      description: Manage Open vSwitch bridges
      name: openvswitch_bridge
      namespace: ""
      version_added: 1.0.0
    openvswitch_db:
      description: Configure open vswitch database.
      name: openvswitch_db
      namespace: ""
      version_added: 1.0.0
    openvswitch_port:
      description: Manage Open vSwitch ports
      name: openvswitch_port
      namespace: ""
      version_added: 1.0.0
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 2.1.1
